### ISSUE TITLE
ADB support

### ISSUE THREAD

**Issue by Duplino** [Macro-Deck-org/Macro-Deck#104]
Add support for Macro Deck Clients via USB through ADB or similar

**Comment by Xenox003** [comment]
Cutout from the Macro Deck discord server:

![Screenshot_20220913-194127_Discord.jpg](https://user-images.githubusercontent.com/68594244/189973077-5d69be20-291a-4f5f-b986-14345f0c5788.jpg)

**Comment by Xenox003** [comment]
If you got any further issues working with the ADB functionality, make sure to re-open this issue or create a new one.

**Comment by NonPlaysGames** [comment]
Worked for me! Thank you so much!!!

**Comment by NonPlaysGames** [comment]
ps: if you get an error saying that adb.exe has more than one host or something like that then go to your task manager and type "adb.exe". End task and follow the before mentioned steps

**Comment by NonPlaysGames** [comment]
![Image](https://github.com/user-attachments/assets/032d0a2a-63dc-45a5-afc7-33754b46da80)
