### ISSUE TITLE
Is there a posibility to change profile with button?

### ISSUE THREAD

**Issue by majkello12** [Macro-Deck-org/Macro-Deck#112]

**Comment by SuchByte** [comment]
Not yet but it's on my todo list.

**Comment by majkello12** [comment]
Thanks for great application, you do a lot of super work to make this. Michal from Poland :)
One more question: How to stop only Spotify music, I can't find action to do this, but I saw on previous version that there was action like this :)

**Comment by SuchByte** [comment]
Added this feature with v2.12.0b3 

The Spotify plugin will be available soon
