### ISSUE TITLE
OBS Plugin Issues

### ISSUE THREAD

**Issue by CatharsisDrums** [Macro-Deck-org/Macro-Deck#231]
This may be a feature request as well as a bug, I'm unsure if it's all one issue or not

1) Whenever I manually connect the MD plugin to OBS, it'll ask for my password. I enter it, it tells me I'm wrong, then asks again and it works fine the second time (this also happens if I have no password enabled). It then continues displaying on the sidebar that MD is disconnected even though the button functions all work as if it is. This is odd, but didn't see anyone mention it yet.

2) It's requiring a manual connection every time I close MD or OBS. It'd be awesome if there was some sort of auto-connect like I've noticed the Voicemeter plugin has. I'm not sure if this lack of function is related to the bug above, but either way, figured I should at least mention it since it's related. As of now it's usable, but definitely more clunky than I feel it's intended to be.

Other than that, I'm loving the new version so far and wish the contributing devs luck going forward <3

**Comment by jbcarreon123** [comment]
It is better to post this issue on the [plugin repo](https://github.com/SuchByte/Macro-Deck-OBS-WebSocket-Plugin).
