### ISSUE TITLE
Macrodeck prohibits input via keyboard

### ISSUE THREAD

**Issue by Der-Flip** [Macro-Deck-org/Macro-Deck#239]
**Describe the bug**
I cannot use any keys on my keyboard, which I have added into macro deck, while macro deck is running.

**To Reproduce**
Steps to reproduce the behaviour:
1. Edit Macro Deck Button
2. Add Key Combination (not via Actions but in the left column, bottom option
3. bind key
4. save
5. try using key on keyboard

**Expected behaviour**
Keyboard key still working.

**Screenshots**
<video src="https://user-images.githubusercontent.com/18213041/172206819-a4063ba1-a477-4d94-a859-45c10a0b8893.mp4" />

**Log file**
[macrodeck2Log.txt](https://github.com/Macro-Deck-org/Macro-Deck/files/8845987/macrodeck2Log.txt)

**Comment by SuchByte** [comment]
I think you misunderstood the function of this feature, this is not a bug.
The assigned hotkey there is to trigger the actions with the selected hotkey. For example you can set something like CTRL+L and when the CTRL+L hotkey is pressed on your keyboard, the actions of this buttons are triggered like when you press the button on the app.

I think what you want is that a hotkey is sent when the action button is pressed. For that you need to add the Hotkey action of the Windows Utils plugin on the right side.
