### ISSUE TITLE
Streamlabs Desktop

### ISSUE THREAD

**Issue by FullSendMCdev** [Macro-Deck-org/Macro-Deck#240]
Having integration with Streamlabs would be great. OBS is very basic and is missing many of the key features many streamers love. 
 This the best free stream deck setup and is really nice with the Web GUI. If it had a few more key features it would compete with many of the paid services.

**Comment by jbcarreon123** [comment]
The StreamLabs OBS Plugin by @RecklessBoon is now on the Extension Store.

REPO: https://github.com/RecklessBoon/Macro-Deck-Streamlabs-OBS-Plugin/tree/main
VERS: 1.0.2
