### ISSUE TITLE
Failed to import the file icon: Method not found

### ISSUE THREAD

**Issue by holafanz** [Macro-Deck-org/Macro-Deck#250]
**Describe the bug**
Dont import a file icon

**To Reproduce**
First, add a button, then select actions in the Windows Utils plugin - run the application, select the application, click ok, and the icon on the export window - yes, after that, instead of exporting the icon, an error occurs

**Expected behavior**
Icon import

**Screenshots**
They don't exist

**Additional context**
They don't exist

**Log file**
[2022-06-25.log](https://github.com/Macro-Deck-org/Macro-Deck/files/8984179/2022-06-25.log)

**Comment by SuchByte** [comment]
Fixed with v1.4.1 of the plugin
