### ISSUE TITLE
Write Text function in Windows Utils not working

### ISSUE THREAD

**Issue by emerysteele** [Macro-Deck-org/Macro-Deck#255]
**Describe the bug**
Can't get write text to write text. Does nothing.

**To Reproduce**
1. Make new macro deck button with windows utils write text function
2. Tap button on client
3. Does not write text to textbox w/cursor in it
4. No error in macro deck

**Expected behavior**
It should work

**Screenshots**
![Macro_Deck_2_u4pV8M8WYj](https://user-images.githubusercontent.com/1169001/178128979-46ab7f99-3dc5-466f-9ff4-5f69a0cf04b8.png)

**Additional context**

**Log file**
[2022-07-09.log](https://github.com/Macro-Deck-org/Macro-Deck/files/9078303/2022-07-09.log)

**Comment by Ceteak** [comment]
Been like this for the last few updates, Installing Ver 2.10.3  reverts back to it working

**Comment by SuchByte** [comment]
Fixed with v.1.4.1 of the plugin

**Comment by emerysteele** [comment]
🙏
