### ISSUE TITLE
The Snipaste screenshot operation of the third party software will cause my actions on the mobile phone to be unresponsive

### ISSUE THREAD

**Issue by BlueLvRen** [Macro-Deck-org/Macro-Deck#267]
**Describe the bug**
I added actions to the snipaste screenshots and mapping functions, but I tried the mapping function after the screenshots and found that the mapping operation could not be responded. 

**To Reproduce**
1. I create two new actions to trigger the press of the button f11 when pressed and the button f10 when pressed, where f11 and f10 are the shortcut keys for screenshot and mapping, respectively.
2. I triggered the first action, f11 was pressed, screenshot selected action normal response.
3. I tried to trigger the second action, F10 was not pressed, no action was triggered.

**Expected behavior**
When I triggered the second action, f10 should have been pressed, but it didn't.

**Screenshots**

**Additional context**
I guess the same problem would occur in other third-party software screenshots, but I didn't test it. Maybe it's an adaptation problem or a underlying priority problem.
The above content has been turned over by machine. If there is any ambiguity, please point out. I hope everything goes well with you.

**Log file**
Please upload the latest log file (Help -> Export latest log)

**Comment by Xenox003** [comment]
Hi there, just to ensure myself: You are using the Windows Utils Module to simulate a Key Press, correct?

**Comment by Xenox003** [comment]
Have you ever tried using https://keyboardchecker.com/ to test your keypresses? There might also be the chance that some other software is blocking the F10 key, does it work when you press it manually?

**Comment by BlueLvRen** [comment]
> Hi there, just to ensure myself: You are using the Windows Utils Module to simulate a Key Press, correct?

yes,it is.

**Comment by BlueLvRen** [comment]
> Hi there, just to ensure myself: You are using the Windows Utils Module to simulate a Key Press, correct?

Yes,it is.

**Comment by BlueLvRen** [comment]
> Have you ever tried using https://keyboardchecker.com/ to test your keypresses? There might also be the chance that some other software is blocking the F10 key, does it work when you press it manually?

For unknown reasons, I cannot test the website you provided normally. I can only provide the operation result of my machine -- I can respond when I press F10 normally, but not when I trigger the analog key through action.

**Comment by Xenox003** [comment]
Can you test any other keyboard checker website/software if it responds to macro deck action

**Comment by BlueLvRen** [comment]
> Can you test any other keyboard checker website/software if it responds to macro deck action

I was going to explain to you the results of my test on another website, but when I repeated what I did on macro deck action yesterday, I found a different result, when f11 could be pressed normally, and so could f10. 
Well, since the problem can not be repeated, I guess it may be my equipment problem, you can pay attention to other problems, I am sorry to take up your energy on this, if the problem occurs again, I will consider describing it to you again. Have a nice day.
