### ISSUE TITLE
Wrong count of loaded plugins

### ISSUE THREAD

**Issue by psyhlo** [Macro-Deck-org/Macro-Deck#270]
When you install plugins the count is correct, but when you delete some of installed plugins, the count remains the same

![Screenshot](https://imgur.com/RtEXMFg.png)

**Comment by SuchByte** [comment]
Actually this count is correct. This count includes the 4 plugins you see there (not Icon Packs) and the 4 internal plugins.

**Comment by psyhlo** [comment]
ok you are right, but that is some how confusing
