### ISSUE TITLE
I can't compile it

### ISSUE THREAD

**Issue by acantuta** [Macro-Deck-org/Macro-Deck#271]
**Describe the bug**
When I try to compile, I get "Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'FCTB 2.16.21' was restored using 'UAP,Version=v10.0.22000, .NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.	Macro Deck 2	D:\Projects\Macro-Deck\Macro Deck 2.csproj	1	
"

**To Reproduce**
1. Go to the main folder
2. Execute "dotnet restore" from Powershell.

**Expected behavior**
Successful restoration

Errors

![image](https://user-images.githubusercontent.com/1783030/181562501-23986a43-4ed9-40aa-93c9-e0a34176d82a.png)

**Comment by SuchByte** [comment]
Remove the post-build event. It does compile but it can‘t copy the dll (which I need for the installer) because your paths are different.
