### ISSUE TITLE
Folder change as a result of a variable change in the "on event" tab is only reflected in the desktop editor (and not on the phone as would be expected)

### ISSUE THREAD

**Issue by ludvigpujsek** [Macro-Deck-org/Macro-Deck#272]
**Describe the bug**
When using the "on event" tab trying to change folders when a certain condition is met (in my case the "Variable changed" option, using a variable from the MediaInfo plugin) will result in only the PC editor changing folders, while the phone will stay in the current folder.

**To Reproduce**
1. On a button go to the "On event" tab
2. Set trigger to "Variable changed" and "media_info_playing_status" or "media_info_is_playing" from the MediaInfo plugin as the variable
3. Set a folder change action
4. When the condition is met (in my case the music playing, but anything else should also "work") the folder only changes in the desktop app, while it remains stuck on the currently open folder on the phone.

**Expected behavior**
When the steps under "To Reproduce" have been made, the MacroDeck client on the phone should change to the selected folder. 
E.g. when music is playing, switch to the folder with music controls. 

**Screenshots**
Button configuration:
![image](https://user-images.githubusercontent.com/69319650/181935954-08c03609-033c-4819-892c-c872e6f48776.png)

Before music plays (nevermind the crossed out buttons, I am yet to figure out what is wrong there):
<img width="901" alt="image" src="https://user-images.githubusercontent.com/69319650/181935969-7b1a2115-e588-42bb-8af5-deee5f1763ac.png">

After music starts playing (the desktop app switches to the music folder, but the phone app stays on the first screen):
![image](https://user-images.githubusercontent.com/69319650/181935990-57b62e07-f9d0-46a9-bc08-ec5d45919a75.png)

**Additional context**

**Log file**
[2022-07-30.log](https://github.com/Macro-Deck-org/Macro-Deck/files/9227058/2022-07-30.log)

**Comment by quirin053** [comment]
Had the same problem, would be really useful to be able to select a device.

**Comment by ludvigpujsek** [comment]
Ah, i see

Yeah, that would be nice 🙂
Thanks for the reply
