### ISSUE TITLE
Press and hold keyboard shortcut

### ISSUE THREAD

**Issue by virgo47** [Macro-Deck-org/Macro-Deck#284]
**Is your feature request related to a problem? Please describe.**
Currently, I can tap an icon and it will send keyboard shortcut (with Windows plugin). But I can't press and hold the icon to keep the shortcut pressed. This would be beneficial for games, flying simulators in my case, where actions like "press and hold for 2 seconds" are quite normal.

**Describe the solution you'd like**
In the easiest setup for a user there should be something like "On hold" action, because this obviously is not On press, nor On release. When such an action is chosen, Windows plugin would offer Hotkey which would be pressed and held for the whole duration of the press. Alternatively, Windows plugin can offer hotkeyOn and Off... but this may be complicated for setup and may offer room for errors (what if user sets on differently than off?).

**Describe alternatives you've considered**
I've googled a bit, found nothing, at this moment, I will use it only for actions that don't require press-n-hold semantics.

**Additional context**
Nothing special... any game where holding a key for a while may bring a benefit. DCS simulator is a good example, because there are so many binds, that using something like Stream Deck (which seems NOT to support press-n-hold either!) - or this fantastic alternative - 
is ideal for less-used functions. It's still available, it can be readable on the display, it plays well with features like icon folders... this is a fantastic alternative to HW controllers - and while less tactile, it is even more flexible.

**Comment by jbcarreon123** [comment]
> **Is your feature request related to a problem? Please describe.** Currently, I can tap an icon and it will send keyboard shortcut (with Windows plugin). But I can't press and hold the icon to keep the shortcut pressed. This would be beneficial for games, flying simulators in my case, where actions like "press and hold for 2 seconds" are quite normal.
> 
> **Describe the solution you'd like** In the easiest setup for a user there should be something like "On hold" action, because this obviously is not On press, nor On release. When such an action is chosen, Windows plugin would offer Hotkey which would be pressed and held for the whole duration of the press. Alternatively, Windows plugin can offer hotkeyOn and Off... but this may be complicated for setup and may offer room for errors (what if user sets on differently than off?).
> 
> **Describe alternatives you've considered** I've googled a bit, found nothing, at this moment, I will use it only for actions that don't require press-n-hold semantics.
> 
> **Additional context** Nothing special... any game where holding a key for a while may bring a benefit. DCS simulator is a good example, because there are so many binds, that using something like Stream Deck (which seems NOT to support press-n-hold either!) - or this fantastic alternative - is ideal for less-used functions. It's still available, it can be readable on the display, it plays well with features like icon folders... this is a fantastic alternative to HW controllers - and while less tactile, it is even more flexible.

Please go to the [plugins repository](https://github.com/SuchByte/Macro-Deck-Windows-Utils-Plugin) and make a issue there.

**Comment by virgo47** [comment]
Oh, sorry, I tried to find that repo, but only among Macro-Deck-org repos... thanks for the pointer.

Now it's there: https://github.com/SuchByte/Macro-Deck-Windows-Utils-Plugin/issues/26
