### ISSUE TITLE
NOT ABLE TO SET ICONS

### ISSUE THREAD

**Issue by LiquidFalco** [Macro-Deck-org/Macro-Deck#290]
*Not able to crate icons*

**To Reproduce**
1. Go to 'edit'
2. Click on 'add an image, and save 

**Expected behavior**
[2022-09-13 Log.txt](https://github.com/Macro-Deck-org/Macro-Deck/files/9562184/2022-09-13.Log.txt)

**Screenshots**

**Additional context**

**Log file**
Please upload the latest log file (Help -> Export latest log)

**Comment by jbcarreon123** [comment]
The template is missing a lot of useful information. I can't reproduce it.

Can you clarify the problem?

**Comment by Xenox003** [comment]
Might be related to https://github.com/Macro-Deck-org/Macro-Deck/issues/263

**Comment by D1ck3sb** [comment]
I have the same problem.
Generally no icons are displayed and I can't create any icons. 
Also a new installation has brought no change. 
Operating system: Win11 22H2

[excerpt logfile.txt](https://github.com/Macro-Deck-org/Macro-Deck/files/9674760/excerpt.logfile.txt)
