### ISSUE TITLE
Macro-deck does not start after upgrading to Windows 11 22H2.

### ISSUE THREAD

**Issue by Sacaruto91** [Macro-Deck-org/Macro-Deck#291]
Hello. I explain what has happened.
I'm a streamer on Twich, and I use Macro-deck daily. After installing the recently released update for Windows 11, the program does not start. I double click and nothing appears. I think it could be due to an incompatibility with the operating system. I hope the problem can be resolved.

Many thanks.

**Comment by SuchByte** [comment]
Hi,

unfortunately I cannot update to 22H2 yet. Please upload the latest log file located in %Appdata%\Macro Deck\logs

Also if you're able to to, take a look at the Windows Event Log to see if there is any error.

**Comment by TheTruckerDarts** [comment]
Same Problem..... After opening the App it chrashed. I send my logfil and the Windows Event Log maybe it could be fixed soon
[2022-10-09.log](https://github.com/Macro-Deck-org/Macro-Deck/files/9740843/2022-10-09.log)
[Crashevent.txt](https://github.com/Macro-Deck-org/Macro-Deck/files/9740844/Crashevent.txt)

**Comment by SuchByte** [comment]
I cannot verify that 22H2 is the issue here. It seems like the Spotify plugin causes Macro Deck to crash. Try to remove the plugin by deleting the plugin in `%Appdata%\Macro Deck\plugins`

**Comment by wirytiox** [comment]
I have 22H2 and it works nice, maybe it is a weird update thing. have you tried reinstalling and importing a backup? (I installed macro deck after updating to 22H2)
