### ISSUE TITLE
Must change ethernet adapter after turn on

### ISSUE THREAD

**Issue by Korzyk** [Macro-Deck-org/Macro-Deck#292]
**Describe the bug**
When computer ip is changed and i turn it on i must change ethernet adapter in macro deck, because it not remember this

**To Reproduce**
1. Turn off computer
2. Restart your router or change ip of your computer
3. Turn on the computer
4. See error of macrodeck

**Expected behavior**
Run normal

**Log file**
[2022-09-27.log](https://github.com/Macro-Deck-org/Macro-Deck/files/9654736/2022-09-27.log)

**Comment by SuchByte** [comment]
This is because the configuration saves the ip address and not the network adapter. Try to assign a static ip address to your computer.
