### ISSUE TITLE
hey, how make a "Ctrl+;" - Windows util don't do that.

### ISSUE THREAD

**Issue by Watchoff** [Macro-Deck-org/Macro-Deck#294]
**Describe the bug**

I'm French. I used french keyboard and french affinity version 

J maked affinity icon for my macrodeck but I have some fonctions, i can't program like "Ctrl+;" . how can i do that ?

![image](https://user-images.githubusercontent.com/114866694/193458434-0a848f92-dc31-4c19-89c1-4765d5751164.png)

**Comment by 1ightmagic** [comment]
Install  Autohotkey plugin。
Select  “ Write and Run AHK Script ”
Type in：Send ^{;}

**Comment by Watchoff** [comment]
YEEEEEEESSSSSSSSSSSSSSSS - Thank you ! I was lost for the second time (macrodeck 1 and macrodeck 2)  !!!!!!!!! 

Just for anyone, you have to install before autohotkey.exe (https://www.autohotkey.com/download/)

**Comment by Watchoff** [comment]
thank you
