### ISSUE TITLE
macro deck started with administrator privileges

### ISSUE THREAD

**Issue by anschein** [Macro-Deck-org/Macro-Deck#297]
I'm using macro deck in win11 with single administrator account,and when I boot up my pc,this warning `macro deck started with administrator privileges' shows up and I need to click to confirm so the macro deck can start,but the autostart with system up is meaningless.
If we have a set to bapass or ignore this warning permanent so they can autostart that would be very nice

**Comment by guyueyueshen** [comment]
I also have this problem..

**Comment by Xenox003** [comment]
Duplicate of https://github.com/Macro-Deck-org/Macro-Deck/issues/287
For any further comments regarding to this issue/enhancement please use the Link above
