### ISSUE TITLE
AutoHotkey Plugin: Error when sending "\"+String

### ISSUE THREAD

**Issue by jadaCamp** [Macro-Deck-org/Macro-Deck#302]
**Describe the bug**
After yesterday's update of the AutoHotkey Plugin, the "send"-function does not send "\\" [backslash] in combination with a string. With the prior version, all sending commands worked properly.

**To Reproduce**
1. Define a new button.
2. AutoHotkey Plugin--> Write an Run AHKv2 Script
3. Enter: "Send \left". Save
4. See error: printing "left" without "\\"

**Expected behavior**
Strings with prefix "\\" should be sent as defined, e.g. "\left"

update:
the command "send {\\}left" leads to an outcome of "\left". IMO it is still a bug

**Comment by SuchByte** [comment]
The AHK Plugin is a community plugin. Please open an issue in the repository of the author of the plugin: https://github.com/jbcarreon123/MacroDeck2-AHKPlugin/issues
