### ISSUE TITLE
Connection via usb

### ISSUE THREAD

**Issue by criquio** [Macro-Deck-org/Macro-Deck#303]
Hi there! I'd like to suggest you consider the possibility of adding usb connection feature to Macro Deck. I had to configure an adb server in order to use it via usb but it has an issue: pc connection gets very slow because it creates an extra network which consumes a large amount of data because it uses a tethering. It kinda makes it impossible to stream if you don't have at least a 500 Mbits of band plan. My plan is 100 Mbits and it delivers about 30Mbits of upload 99% of the time. With Macro Deck using tethering in order to work via usb it slows donw to 3 Mbits of upload and 10Mbits of download. Macro Deck should implement usb connection. It's much better than wi-fi connection. As a comparison Deckboard has usb connection and I use it without loss of network speed on pc because it does not create extra network and does not need tethering in order to work. So I have to use only Deckboard which is a pity because I'd like to use Macro Deck.

I really hope Macro Deck implements this feature in next update(s) even if you consider charge a few dollars for it. I paid $20 for Deckboard Pro and I'd pay something around this value for this extra feature on Macro Deck too.

Cheers!

**Comment by jbcarreon123** [comment]
There is a USB connection on Macro Deck.

**Comment by MGTRFarabler** [comment]
how do you connect via usb?

**Comment by criquio** [comment]
> 

Actually there's not a real usb connection. By the way, the MD developer himself told me that the software does not have usb feature but he is working on it for the next versions. As I said in my previous message, I can connect via usb but not directly. I have to create a tethering usb connection which creates a network between the mobile and the computer. It was slowing down my pc Internet speed. I found out this was happening because my pc was using the mobile network instead of its own network board. I solved the problem setting its network as primary.

**Comment by criquio** [comment]
> how do you connect via usb?

You have to activate the usb debug and usb tethering in order to create a network between pc and mobile. In order to avoid that your pc slows down Internet speed, maybe you have to configure its own network as primary. I'm gonna try to show you how although I'm from Brazil and I'm not sure what are the features name in English. Try following this simple steps:

1. Press Window Key on your pc keyboard;
2. Type network and see weather it shows something like "Show network connection". You may try the full name too;
3. Click on the showed option;
4. Right click the your pc correct network board Ethernet connection;
5. Click on Properties;
6. Search, in the list, "IP protocol Version 4 (TCP /IPv4)" and click it;
7. Click the Properties button;
8. Click the advanced button;
9. Uncheck the last option "Automatic metric" and type 10 in the field right below it.
10. Click OK

This might solve the Internet slow speed.
