### ISSUE TITLE
Binds on the F13-F24 keys do not work

### ISSUE THREAD

**Issue by plhappylemonpl** [Macro-Deck-org/Macro-Deck#315]
As the topic. Binds used to work, now they don't work
![image](https://user-images.githubusercontent.com/46198081/200118278-858e8515-80f0-4f8c-948d-85e01d605ad9.png)
Plugin is ON
[
Włączony = ON
]

** Name of the plugin **
Windows Utils v1.4.1

** Version **
1.4.1

** GitHub repository **
Windows Utils (idk where is link this plugin, but this is "official")

** Dependencies **
Macro Deck version: 2.12.0

**Comment by SuchByte** [comment]
Cannot reproduce this issue.
![Screenshot_1](https://user-images.githubusercontent.com/45011179/200119354-d584b4b0-32c6-4007-9f3b-f75059dbe83e.png)
![Screenshot_2](https://user-images.githubusercontent.com/45011179/200119356-4bf9c7df-eb95-4483-b310-9e68831b6651.png)

Also this is the wrong repository. The repository for the Windows Utils plugin can be found here: https://github.com/SuchByte/Macro-Deck-Windows-Utils-Plugin
