### ISSUE TITLE
Stuck on waiting for approval

### ISSUE THREAD

**Issue by vandrw** [Macro-Deck-org/Macro-Deck#320]
**Describe the bug**
Whenever I attempt to connect to my Macro Deck server from the Android app, I am stuck on the following prompt:
```
Waiting for the user to accept the connection on the host...
```
The host has already accepted the connection, and the Android client appears to be connected into the Known devices list.

The constant reconnects also seem to affect the quality of my internet. I have a slight suspicion that it attempt to send packets over and over again, which basically acts as a mini-DDoS attack.

**To Reproduce**
1. Open Macro Deck server on Windows
2. Add the IP and port to the client and connect
3. Accept the connection on the host
4. Wait

**Expected behavior**
The client should automatically connect to the server.

**Screenshots**
None.

**Additional context**
Windows App version: 2.12.0
Android client version: 2.4.1-beta

**Log file**
[log.txt](https://github.com/Macro-Deck-org/Macro-Deck/files/9995623/log.txt)

**Comment by jbcarreon123** [comment]
Can you try restarting Macro Deck to Debug Console mode
```cmd
"C:/Program Files/Macro Deck/Macro Deck 2.exe" --show --debug-console
```
Then setting the log-level to Trace and reconnect your device?

After that, comment the log here

**Comment by vandrw** [comment]
Hi! Thanks for your time!

I managed to fix this by reinstalling the Windows app. I cannot seem to replicate the issue any more.

The Android client now correctly loads the buttons after displaying the previously described message for a short while. I will keep monitoring, and I'll make sure to get the trace logs if it happens again.

**Comment by vandrw** [comment]
Hi! It seems that the issue is related to failing to obtain the buttons.

```
11:07:32 [Macro Deck] [Info] >> Set log level to Trace
11:07:50 [Macro Deck] [Trace] >> Received method: CONNECTED
11:07:50 [Macro Deck] [Info] >> Connection request from U0JU8ZXJ4
11:07:50 [Macro Deck] [Trace] >> SoftwareClientMessage: {
  "Method": "GET_CONFIG",
  "Rows": 6,
  "Columns": 10,
  "ButtonSpacing": 3,
  "ButtonRadius": 40,
  "ButtonBackground": true,
  "Brightness": 0.3,
  "AutoConnect": false,
  "WakeLock": "Connected",
  "SupportButtonReleaseLongPress": true
}
11:07:50 [Macro Deck] [Info] >> U0JU8ZXJ4 connected
11:07:50 [Macro Deck] [Trace] >> Received method: GET_BUTTONS
11:08:13 [Macro Deck] [Info] >> U0JU8ZXJ4 connection closed
11:08:13 [Macro Deck] [Info] >> U0JU8ZXJ4 connection closed
```

After the connection is closed, the Android device is still printing "Waiting for the user to accept the connection on the host..."

Is this related to having too many buttons? I would expect being returned to the default menu on the device once the connection is closed.

Happy holidays, and thank you once again for your time!
