### ISSUE TITLE
Plugin download doesn't work

### ISSUE THREAD

**Issue by xMimicria** [Macro-Deck-org/Macro-Deck#352]
Plugin downloading does not work in the application, as well as on the site.

![image](https://user-images.githubusercontent.com/92284789/213917214-16ab0ee4-451b-418d-b43c-319a6348a907.png)
![image](https://user-images.githubusercontent.com/92284789/213917229-9bb84f24-9920-454e-81b7-19d918e0bc7a.png)

[2023-01-22.log](https://github.com/Macro-Deck-org/Macro-Deck/files/10474465/2023-01-22.log)

**Comment by SuchByte** [comment]
This issue is fixed now.
