### ISSUE TITLE
Check sum doesn't match on every of icon packs

### ISSUE THREAD

**Issue by Sergsw74** [Macro-Deck-org/Macro-Deck#355]
**Describe the bug**
Check sum doesn't match on every of icon packs

**To Reproduce**
1. Go to 'plugins'
2. Click on 'online'
3. Click on 'Icon packs'
4. Try to install "Macro Deck colorful generic icons"
5. We'll notification with error (log file in attachment)

**Expected behavior**
Icon pack imported

**Screenshots**
![MicroDesc-error](https://user-images.githubusercontent.com/119474977/214210488-857593ef-32a7-4ad1-84fc-feaa485a4764.png)

**Additional context**
OS: Win 11
MicroDesc ver: 2.12.0

**Log file**
Please upload the latest log file (Help -> Export latest log)
[2023-01-23.log](https://github.com/Macro-Deck-org/Macro-Deck/files/10486262/2023-01-23.log)

**Comment by Gen-tastic** [comment]
Same Issue here

OS: Win10 Pro

[2023-01-24.txt](https://github.com/Macro-Deck-org/Macro-Deck/files/10493069/2023-01-24.txt)

**Comment by Roloplay** [comment]
the bug is in all cases, I tested on 2 laptops with win 10 and 2 with win 11 and it does not allow to download icons.

**Comment by SuchByte** [comment]
Is is fixed now.
