### ISSUE TITLE
Macro Deck started with administrator privileges

### ISSUE THREAD

**Issue by hellishvictor** [Macro-Deck-org/Macro-Deck#358]
Hi, it shows:
**"Macro Deck started with administrator privileges,
It's not recommended to start Macro Deck with administrator privileges".**
Then it closes. I'm on Win7 x64.
Cheers.

**Comment by SuchByte** [comment]
Please note that Macro Deck does not support Windows 7 because it is not worth it to test and optimize it for such an old OS. Macro Deck might try to access some API that is not available on Windows 7 and because of this, it crashes.
